openapi: 3.0.1
info:
  title: Bookshop API
  description: Bookshop API
  version: 1.0.0
paths:
  /books:
    get:
      summary: Get a list of books
      responses:
        '200':
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        author:
          $ref: '#/components/schemas/Author'
        genre:
          type: string
        price:
          type: number
          format: double
        pages:
          type: integer
        visitCount:
          type: integer
        available:
          type: boolean
        stock:
          type: integer
    Author:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string